In [45]:
import numpy as np
import random
from time import time

1. Een 5x5 identiteitsmatrix met integer waardes. 

In [17]:
np.eye(5, dtype=np.int32)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

2. Een 5x5 matrix met float waardes en overal nul behalve op de 2e nevendiagonaal 

In [19]:
np.eye(6, dtype=np.int32)[1:,0:-1]

array([[0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0]])

3. Een array die van 0 tot 150 gaat met stapgrootte 5 en integer waardes heeft. 

In [12]:
np.arange(0 ,150, 5, dtype=int )

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145])

4. Een array die in het interval [0,100] 200 gelijk verdeelde punten neemt. 

In [20]:
np.linspace(0 ,100, 200 )

array([  0.        ,   0.50251256,   1.00502513,   1.50753769,
         2.01005025,   2.51256281,   3.01507538,   3.51758794,
         4.0201005 ,   4.52261307,   5.02512563,   5.52763819,
         6.03015075,   6.53266332,   7.03517588,   7.53768844,
         8.04020101,   8.54271357,   9.04522613,   9.54773869,
        10.05025126,  10.55276382,  11.05527638,  11.55778894,
        12.06030151,  12.56281407,  13.06532663,  13.5678392 ,
        14.07035176,  14.57286432,  15.07537688,  15.57788945,
        16.08040201,  16.58291457,  17.08542714,  17.5879397 ,
        18.09045226,  18.59296482,  19.09547739,  19.59798995,
        20.10050251,  20.60301508,  21.10552764,  21.6080402 ,
        22.11055276,  22.61306533,  23.11557789,  23.61809045,
        24.12060302,  24.62311558,  25.12562814,  25.6281407 ,
        26.13065327,  26.63316583,  27.13567839,  27.63819095,
        28.14070352,  28.64321608,  29.14572864,  29.64824121,
        30.15075377,  30.65326633,  31.15577889,  31.65

5. Een 10x5 matrix met allemaal nullen (van type float). Maak dezelfde matrix nogmaals maar nu met type int. 

In [23]:
np.zeros((10,5) , dtype=float) , np.zeros((10,5) , dtype=int)

(array([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]),
 array([[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]))

6. Een 3x4 matrix gevuld met de waarde drie van type int. 

In [25]:
np.full((3,4), 3 , dtype=int)

array([[3, 3, 3, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

7. Een lege 4x4 matrix, een keer met ints en een keer met floats. 
Bekijk ook even welke waardes erin zitten. 

In [28]:
np.empty((4,4), dtype=int), np.empty((4,4), dtype=float)

(array([[        0,         0,         0,         0],
        [        0,         0,         0,         0],
        [        0,         0,      1652,         0],
        [        0, 829554906,         0,       105]]),
 array([[2.37663529e-312, 2.16443571e-312, 2.29175545e-312,
         8.48798317e-313],
        [1.08221785e-312, 1.10343781e-312, 9.33678148e-313,
         1.12465777e-312],
        [9.33678148e-313, 2.12199579e-312, 2.56761491e-312,
         2.14321575e-312],
        [2.22809558e-312, 2.46151512e-312, 1.86921279e-306,
         1.24610723e-306]]))

8. Een array met 10 waardes uit de standaard normale verdeling (notatie: 𝑁(0,1)). 
   
**Extra:** Vergelijk de snelheid tussen het genereren van random getallen in een for loop en in 1 
keer door de shape parameter te gebruiken. 

In [31]:
np.random.normal(0, 1, size=10)

array([-0.6875749 ,  1.44750053, -0.60191069, -0.3092591 ,  0.5195179 ,
       -0.23501884, -2.00138514,  1.49679867,  0.77970097, -0.28805958])

extra

In [58]:
%timeit [ random.random() for _ in range(10**8)  ]

100 ns ± 19.8 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [59]:
%timeit np.random.normal(0, 1, size=10**8)

65.7 ns ± 2.28 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


9. Vergelijk de snelheid tussen universele functies & loops (maak gebruik van %timeit) 
    
**Voorbeeld:** maak 2 grote numpy arrays aan en tel deze op; enerzijds via een universele 
functie anderzijds via een lus. 

In [61]:
%timeit np.zeros(500000) + np.full(500000, 5) 

114 ns ± 4.61 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [62]:
def t():
   a = np.array([])
   for n in np.zeros(500000):
      np.append(a,[n+5])
%timeit t()

2.29 s ± 48.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
